displayName=Dry Streak Tracker
author=Harry Styles
description=See exactly how dry you are. Track current and longest dry streaks, uniques, pets, and recent drops across supported bosses, raids, skilling activities, and more! Now with notifications and Discord integration.
tags=dry,dry streak,streak,streak tracker,dryness tracker,tracker,dryness,killcount,kc,kc tracker, harry styles
version=1.1.1
plugins=com.harrystyles.drystreaktracker.DryStreakTrackerPlugin
build=standard