displayName=Dry Streak Tracker
author=Harry Styles
description=Tracks your current and longest dry streaks between unique drops at almost all supported bosses, raids, and other meaningful encounters.
tags=dry,dry streak,streak,streak tracker,dryness tracker,tracker,dryness,killcount,kc,kc tracker, harry styles
version=1.0.1
plugins=com.harrystyles.drystreaktracker.DryStreakTrackerPlugin
build=standard