displayName=Dry Streak Tracker
author=Harry Styles
description=A simple dry streak tracker plugin, used to track your killcount since your last unique. Works at all bosses and raids.
tags=dry, dry streak, tracker, dryness, killcount, kc, kc tracker
version=1.0.1
plugins=com.harrystyles.drystreaktracker.DryStreakTrackerPlugin
build=standard